services:
  - type: web
    name: telegram-video-bot
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.10
    healthCheckPath: /
